export const free = {
  name: 'Free',
  price: 0,
  type: 'Monthly',
  features: {
    available: [
      '10 forms',
      '100 submissions per month',
      '0 Collaborators',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      'SMTP Intergration',
      'Zapier Integrations',
      '1 Google Sheets Integration',
      'Accept Payments (1% commission)',
      '1 Webhook',
      'Basic Analytics',
    ],
    unavailable: [
      'Question Branching & Logic Jumps',
      'Brandkit',
      'File Uploads',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'Signatures',
      'API Access',
      'Custom domain',
    ],
  },
}

export const personalMonthly = {
  name: 'Personal',
  price: 13,
  type: 'Monthly',
  features: {
    available: [
      'Unlimited forms',
      '1k submissions per month',
      '5 Collaborators',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      '50 Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      '1 GB File Uploads',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'Signatures',
    ],
    unavailable: ['API Access', 'Custom domain'],
  },
}

export const businessMonthly = {
  name: 'Business',
  price: 49,
  type: 'Monthly',
  features: {
    available: [
      'Unlimited forms',
      '15k submissions per month',
      'Unlimited Collaborators',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      'Unlimited Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      '50 GB File Uploads',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'Signatures',
      'API Access',
      'Custom domain',
    ],
    unavailable: [],
  },
}

export const freeYearly = {
  name: 'Free',
  price: 0,
  type: 'Yearly',
  features: {
    available: [
      '10 forms',
      '100 submissions per month',
      '0 Collaborators',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      'SMTP Intergration',
      'Zapier Integrations',
      '1 Google Sheets Integration',
      'Accept Payments (1% commission)',
      '1 Webhook',
      'Basic Analytics',
    ],
    unavailable: [
      'Question Branching & Logic Jumps',
      'Brandkit',
      'File Uploads',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'Signatures',
      'API Access',
      'Custom domain',
    ],
  },
}

export const personalYearly = {
  name: 'Personal',
  price: 12,
  type: 'Yearly',
  features: {
    available: [
      'Unlimited forms',
      '1k submissions per month',
      '5 Collaborators',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      '50 Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      '1 GB File Uploads',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'Signatures',
    ],
    unavailable: ['API Access', 'Custom domain'],
  },
}

export const businessYearly = {
  name: 'Business',
  price: 45,
  type: 'Yearly',
  features: {
    available: [
      'Unlimited forms',
      '15k submissions per month',
      'Unlimited Collaborators',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      'Unlimited Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      '50 GB File Uploads',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'Signatures',
      'API Access',
      'Custom domain',
    ],
    unavailable: [],
  },
}
