export const free = {
  name: 'Free',
  price: 0,
  type: 'Monthly',
  features: {
    available: [
      '10 forms',
      '100 submissions per month',
      'Formester Branding on the form',
      '0 Collaborators',
      '100 MB File Uploads',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      '10 Signatures',
      'SMTP Intergration',
      'Zapier Integrations',
      '1 Google Sheets Integration',
      'Accept Payments (1% commission)',
      '1 Webhook',
      'Basic Analytics',
    ],
    unavailable: [
      'Question Branching & Logic Jumps',
      'Brandkit',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'API Access',
      'Custom domain',
    ],
  },
}

export const personalMonthly = {
  name: 'Personal',
  price: 13,
  type: 'Monthly',
  features: {
    available: [
      'Unlimited forms',
      '1k submissions per month',
      'No Formester Branding',
      '5 Collaborators',
      '1 GB File Uploads',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      '250 Signatures',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      '50 Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
    ],
    unavailable: ['API Access', 'Custom domain'],
  },
}

export const businessMonthly = {
  name: 'Business',
  price: 49,
  type: 'Monthly',
  features: {
    available: [
      'Unlimited forms',
      '15k submissions per month',
      'No Formester Branding',
      'Unlimited Collaborators',
      '50 GB File Uploads',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      '2,500 Signatures',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      'Unlimited Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'API Access',
      'Custom domain',
    ],
    unavailable: [],
  },
}

export const freeYearly = {
  name: 'Free',
  price: 0,
  type: 'Yearly',
  features: {
    available: [
      '10 forms',
      '100 submissions per month',
      'Formester Branding on the form',
      '0 Collaborators',
      '100 MB File Uploads',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      '10 Signatures',
      'SMTP Intergration',
      'Zapier Integrations',
      '1 Google Sheets Integration',
      'Accept Payments (1% commission)',
      '1 Webhook',
      'Basic Analytics',
    ],
    unavailable: [
      'Question Branching & Logic Jumps',
      'Brandkit',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'API Access',
      'Custom domain',
    ],
  },
}

export const personalYearly = {
  name: 'Personal',
  price: 12,
  type: 'Yearly',
  features: {
    available: [
      'Unlimited forms',
      '1k submissions per month',
      'No Formester Branding',
      '5 Collaborators',
      '1 GB File Uploads',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      '250 Signatures',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      '50 Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
    ],
    unavailable: ['API Access', 'Custom domain'],
  },
}

export const businessYearly = {
  name: 'Business',
  price: 45,
  type: 'Yearly',
  features: {
    available: [
      'Unlimited forms',
      '15k submissions per month',
      'No Formester Branding',
      'Unlimited Collaborators',
      '50 GB File Uploads',
      'Spam Protection',
      'Access to Template library',
      'Self Email Notifications',
      'Respondent Email Notifications',
      'Redirect to URL',
      'Hidden Fields',
      '2,500 Signatures',
      'SMTP Intergration',
      'Zapier Integrations',
      'Unlimited Google Sheets Integration',
      'Accept Payments (0% commission)',
      'Unlimited Webhooks',
      'Advanced Analytics',
      'Question Branching & Logic Jumps',
      'Brandkit',
      'Custom meta information',
      'Add script to page - GTM, GA, Pixel',
      'API Access',
      'Custom domain',
    ],
    unavailable: [],
  },
}
