/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './components/**/*.{vue,js,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './composables/**/*.{js,ts}',
    './utils/**/*.{js,ts}',
    './app.vue',
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      fontFamily: {
        primary: 'var(--font-primary)',
        display: 'var(--font-display)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        'fs-tiny': 'var(--fs-tiny)',
        'fs-xs':   'var(--fs-xs)',
        'fs-sm':   'var(--fs-sm)',
        'fs-md':   'var(--fs-md)',
        'fs-lg':   'var(--fs-lg)',
        'fs-xl':   'var(--fs-xl)',
        'fs-2xl':  'var(--fs-2xl)',
        'fs-3xl':  'var(--fs-3xl)',
      },
      lineHeight: {
        'lh-xs':  'var(--lh-xs)',
        'lh-sm':  'var(--lh-sm)',
        'lh-md':  'var(--lh-md)',
        'lh-lg':  'var(--lh-lg)',
        'lh-xl':  'var(--lh-xl)',
        'lh-2xl': 'var(--lh-2xl)',
      },
      colors: {
        // Override/extend Tailwind's default violet with our brand tokens
        violet: {
          25:  'var(--violet-25)',
          50:  'var(--violet-50)',
          100: 'var(--violet-100)',
          300: 'var(--violet-300)',
          500: 'var(--violet-500)',
          600: 'var(--violet-600)',
          700: 'var(--violet-700)',
        },
        // Override/extend Tailwind's default gray with our neutral scale
        gray: {
          25:  'var(--gray-25)',
          50:  'var(--gray-50)',
          100: 'var(--gray-100)',
          200: 'var(--gray-200)',
          300: 'var(--gray-300)',
          400: 'var(--gray-400)',
          500: 'var(--gray-500)',
          700: 'var(--gray-700)',
          900: 'var(--gray-900)',
        },
        // Foreground / text semantic tokens
        fg: {
          1:      'var(--fg-1)',
          2:      'var(--fg-2)',
          3:      'var(--fg-3)',
          muted:  'var(--fg-muted)',
          strong: 'var(--fg-strong)',
        },
        // Semantic status colors
        error: {
          DEFAULT: 'var(--error)',
          10:      'var(--error-10)',
          50:      'var(--error-50)',
        },
        success: {
          DEFAULT: 'var(--success)',
          10:      'var(--success-10)',
          700:     'var(--success-700)',
        },
        warning: {
          400: 'var(--warning-400)',
          500: 'var(--warning-500)',
          600: 'var(--warning-600)',
        },
      },
      borderRadius: {
        'r-sm':   'var(--r-sm)',
        'r':      'var(--r)',
        'r-md':   'var(--r-md)',
        'r-lg':   'var(--r-lg)',
        'r-xl':   'var(--r-xl)',
        'r-2xl':  'var(--r-2xl)',
        'r-3xl':  'var(--r-3xl)',
        'r-half': 'var(--r-half)',
        'r-full': 'var(--r-full)',
      },
      spacing: {
        'space-1':  'var(--space-1)',
        'space-2':  'var(--space-2)',
        'space-3':  'var(--space-3)',
        'space-4':  'var(--space-4)',
        'space-5':  'var(--space-5)',
        'space-6':  'var(--space-6)',
        'space-7':  'var(--space-7)',
        'space-8':  'var(--space-8)',
        'space-9':  'var(--space-9)',
        'space-10': 'var(--space-10)',
        'space-11': 'var(--space-11)',
        'space-12': 'var(--space-12)',
        'space-14': 'var(--space-14)',
        'space-16': 'var(--space-16)',
        'space-18': 'var(--space-18)',
        'space-20': 'var(--space-20)',
        'space-24': 'var(--space-24)',
        'space-25': 'var(--space-25)',
        'space-30': 'var(--space-30)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
}
