<template>
  <div class="container py-5 px-2">
    <div class="row">
        <div class="heading d-flex flex-column align-items-center text-center">
            <h2 class="section__heading">Simple 3 step: How to create forms with Formester section</h2>
            <p class="hero__subheading">Skip the hassle of learning how to create HTML forms from scratch. With Formester, you can concentrate on the questions you want to ask and easily build free online forms. Increase your response rates with our user-friendly form creator!</p>
        </div>

        <div class="mt-md-5 d-flex flex-column">
            <div v-for="(feature, idx) in features" :key="idx" class="d-flex mt-5  section">
                <div class="col-6">
                    <span class="step__heading">{{ feature.step }}</span>
                    <h3 class="section__heading">{{ feature.title }}</h3>
                    <span class="step__description">{{ feature.description }}</span>
                </div>
                <div class="col-5 m-auto">
                    <img 
                        :src="require(`../assets/images/${feature.imageSrc}`)"
                        class="img-fluid my-auto"
                        alt=""
                    >
                </div>
            </div>
        </div>
    </div>
  </div>
</template>

<script>
export default {
    data(){
        return {
            features: [
                {
                    step: 'Step 1',
                    title: 'Create a Custom Form',
                    description:"Open the online form maker in Formester. Decide if you want to start with a blank page or use one of the available pre-designed templates. Combine blocks to create a survey, quiz, registration form, online order form, or any other custom web form. Add standard fields like Name, Email, Phone, Date, Text Input, or File Upload by simply dragging and dropping these blocks into your form. Create multiple choice questions, drop-down lists, ratings, and scales – all with just a few clicks. Once your questions are ready, open the form designer. Choose a built-in form design theme that suits your preferences. Customize the colors, fonts, and buttons until you achieve a web form design that truly represents your brand! That's it – your form is ready.",
                    imageSrc: 'features/three-steps-create-form/step1.png',
                    altText: 'Formester values for money',
                },
                {
                    step: 'Step 2',
                    title: 'Publish and Share',
                    description:"Activate the form in the Publish section so that people can view and fill it out. Now let everyone access your online form: Add the link to the form page to a button on your website. Alternatively, share a direct link to your form on social networks. If you need a website form, use the embed code that is automatically generated by Formester's website form creator. Simply copy and paste it to the desired web page – no HTML coding required. Whichever sharing method you choose, there's no need to set up any additional server integrations. Everything will be processed through Formester's software.",
                    imageSrc: 'features/three-steps-create-form/step2.png',
                    altText: 'no loading screen which makes experience faster',
                },
                {
                    step: 'Step 3',
                    title: 'Gather and Analyze Responses',
                    description:"You don't have to constantly check your dashboard for new responses – you'll receive email notifications when submissions occur. Sit back and get to know your customers one person at a time. Export results as Excel documents or Google Sheets for analysis at your convenience. Alternatively, evaluate key stats and response data in informative visualizations through Formester's web interface. With this valuable data, you can plan ahead for the next steps of your project or business!",
                    imageSrc: 'features/three-steps-create-form/step3.png',
                    altText: 'we provide wide customization with numbers of templates',
                },
                
            ]
        }
    }
}
</script>

<style scoped>
.subheading__text {
    font-size: 16px;
    margin-top: 12px;
}
.step__heading {
    color: var(--clr-primary);
    font-weight: 700;
    margin-bottom: 8px;
}
.step__description {
    font-size: 15px;
    font-weight: 500;
}
.step__circle {
    position: absolute;
    top: 50%;
    right: 50%;
}
.section:nth-child(2) {
   flex-direction: row-reverse;
}
</style>